apiVersion: v1
data:
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQVZKR0dZRkpJUkU1Q05aSFMKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gdXdRZnk0a3Y5Z09aQU5YMmpCV29SZE9FRnE4b29UNW1XUTF1d2NWdgo=
kind: Secret
metadata:
  name: aws-secret
  namespace: default
type: Opaque
